{
 "title": "OVN Central / North Daemon",
 "description": "OVN Central component : North Daemon",
 "tags": [
  "ovn",
  "ovn-northd"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(ovn_northd_build_info, instance)"
    }
   },
   { "name": "topk", "label": "topk", "query": "1,3,5,10,20,10000" }
  ]
 },
 "panels": [
  { "title": "North Daemon", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DB CONN STATUS",
   "type": "bargauge",
   "description": "Connection status of ovn-northd to NB/SB",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ovn_northd_sb_connection_status",
     "legendFormat": "SB {{instance}}"
    },
    {
     "expr": "ovn_northd_nb_connection_status",
     "legendFormat": "NB {{instance}}"
    }
   ]
  },
  {
   "title": "NORTHD STATUS",
   "type": "stat",
   "description": "Overall North daemon status: STANDBY, ACTIVE or PAUSED",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ovn_northd_status", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "BUILD INFO",
   "type": "table",
   "description": "OVN northd build info",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "ovn_northd_build_info", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "TXN ERROR RATE/SEC (TOP $topk)",
   "type": "timeseries",
   "description": "Transaction error rate",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($topk, rate(ovn_northd_txn_error[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TXN INCOMPLETE RATE/SEC (TOP $topk)",
   "type": "timeseries",
   "description": "Transaction incomplete rate",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($topk, rate(ovn_northd_txn_incomplete[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}