{
 "title": "OVN Host / Controller",
 "description": "OVN Host component : Controller",
 "tags": [
  "ovn",
  "ovn-controller"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(ovn_controller_build_info, instance)"
    }
   },
   { "name": "topk", "label": "topk", "query": "1,3,5,10,20,10000" }
  ]
 },
 "panels": [
  { "title": "Host Controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "INFO",
   "type": "table",
   "description": "OVN/OVS versions of software",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "ovn_controller_build_info", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "CONTROLLER CONNECTION STATUS",
   "type": "bargauge",
   "description": "Controller connection status to Southbound DB",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ovn_controller_southbound_database_connected)",
     "legendFormat": "CONNECTED"
    },
    {
     "expr": "sum(1 - ovn_controller_southbound_database_connected)",
     "legendFormat": "NOT CONNECTED"
    }
   ]
  },
  {
   "title": "LFLOW RUN RATE/SEC (TOP $topk)",
   "type": "timeseries",
   "description": "Logical flow translations per second",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($topk, rate(ovn_controller_lflow_run{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TXN ERROR RATE/SEC (TOP $topk)",
   "type": "timeseries",
   "description": "Controller transaction error rate",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($topk, rate(ovn_controller_txn_error{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TXN INCOMPLETE RATE/SEC (TOP $topk)",
   "type": "timeseries",
   "description": "Controller transaction incomplete rate",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($topk, rate(ovn_controller_txn_incomplete{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TXN SUCCESS RATE/SEC (TOP $topk)",
   "type": "timeseries",
   "description": "Controller transaction success rate",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($topk, rate(ovn_controller_txn_success{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TXN UNCHANGED RATE/SEC (TOP $topk)",
   "type": "timeseries",
   "description": "Controller transaction unchanged rate",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($topk, rate(ovn_controller_txn_unchanged{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TXN ABNORMAL (TOP $topk)",
   "type": "timeseries",
   "description": "Controller abnormal transactions",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk($topk, ovn_controller_txn_error{instance=~\"$instance\"})",
     "legendFormat": "error {{instance}}"
    },
    {
     "expr": "topk($topk, ovn_controller_txn_aborted{instance=~\"$instance\"})",
     "legendFormat": "aborted {{instance}}"
    },
    {
     "expr": "topk($topk, ovn_controller_txn_try_again{instance=~\"$instance\"})",
     "legendFormat": "try_again {{instance}}"
    },
    {
     "expr": "topk($topk, ovn_controller_txn_uncommitted{instance=~\"$instance\"})",
     "legendFormat": "uncommitted {{instance}}"
    }
   ]
  },
  {
   "title": "Controller Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "RCONN QUEUED/SEC (TOP $topk)",
     "type": "timeseries",
     "description": "RCONN queued per second",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "topk($topk, rate(ovn_controller_rconn_queued{instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "RCONN OVERFLOW/SEC (TOP $topk)",
     "type": "timeseries",
     "description": "RCONN overflow per second",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "topk($topk, rate(ovn_controller_rconn_overflow{instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "RCONN SENT/SEC (TOP $topk)",
     "type": "timeseries",
     "description": "RCONN sent per second",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "topk($topk, rate(ovn_controller_rconn_sent{instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "RCONN DISCARDED/SEC (TOP $topk)",
     "type": "timeseries",
     "description": "RCONN discarded per second",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "topk($topk, rate(ovn_controller_rconn_discarded{instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "VCONN SENT/SEC (TOP $topk)",
     "type": "timeseries",
     "description": "VCONN sent per second",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "topk($topk, rate(ovn_controller_vconn_sent{instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "VCONN RECEIVED/SEC (TOP $topk)",
     "type": "timeseries",
     "description": "VCONN received per second",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "topk($topk, rate(ovn_controller_vconn_received{instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "VCONN OPEN/SEC (TOP $topk)",
     "type": "timeseries",
     "description": "VCONN open per second",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "topk($topk, rate(ovn_controller_vconn_open{instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "STREAM OPEN/SEC (TOP $topk)",
     "type": "timeseries",
     "description": "Stream open per second",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "topk($topk, rate(ovn_controller_stream_open{instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Open Flow Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "LFLOW RUN/SEC (TOP $topk)",
     "type": "timeseries",
     "description": "Logical flow table translation rate",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "topk($topk, rate(ovn_controller_lflow_run{instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}