{
 "title": "Host / OVS",
 "description": "sss",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(ovs_build_info, instance)"
    }
   },
   {
    "name": "bridge",
    "label": "Bridge",
    "query": {
     "query": "label_values(ovs_vswitchd_bridge{instance=~\"$instance\"},bridge)"
    }
   },
   {
    "name": "interface",
    "label": "Interface",
    "query": {
     "query": "label_values(ovs_vswitchd_interface_driver_name{instance=~\"$instance\", bridge=~\"$bridge\"},interface)"
    }
   },
   { "name": "topk", "label": "topk", "query": "5, 10, 20, 100, 1000, 2000" }
  ]
 },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OVS BUILD INFO",
   "type": "table",
   "description": "Shows the summary of various ovs versions and number of nodes having a specific OVS version",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(ovs_build_info) by (version)"
    }
   ]
  },
  {
   "title": "INTERFACE DRIVER VERSION",
   "type": "table",
   "description": "Shows summary of various Interface's network driver versions with number of interfaces having that specific version",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(ovs_vswitchd_interface_driver_version) by (bridge, version)"
    }
   ]
  },
  {
   "title": "INTERFACE FIRMWARE VERSION",
   "type": "table",
   "description": "Shows summary of various Firmware version of the network adapter and number of interfaces having that specific versions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum(ovs_vswitchd_interface_firmware_version) by (bridge, version)"
    }
   ]
  },
  {
   "title": "OVS Daemon (TOP K)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization Rate (TOP K)",
     "type": "timeseries",
     "description": "ovs-vswitchd process CPU usage",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "topk($topk, sum(rate(namedprocess_namegroup_cpu_seconds_total{groupname=\"ovs-vswitchd\",instance=~\"$instance\"}[$__rate_interval])) by (instance) * 100)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory Utilization (TOP K)",
     "type": "timeseries",
     "description": "ovs-vswitchd process RSS memory",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "topk($topk, namedprocess_namegroup_memory_bytes{job=\"process-exporter\",groupname=\"ovs-vswitchd\",pod=~\"process-exporter-.*\",memtype=\"resident\",instance=~\"$instance\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Flow Lookups Failed and Discarded (worst) (TOP K)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "pps", "label": "Packets Dropped / sec" }
     ],
     "targets": [
      {
       "expr": "topk($topk, sum(\n    rate(\n      ovs_vswitchd_dp_flows_lookup_lost{\n\t      instance=~\"$instance\"\n\t  }[$__rate_interval:]\n  )\n) by (instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Flow Lookups Processed in Userspace (bad) (TOP K)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "pps", "label": "Packets Missed / sec" }
     ],
     "targets": [
      {
       "expr": "topk($topk, sum(\n    rate(\n      ovs_vswitchd_dp_flows_lookup_missed{\n\t      instance=~\"$instance\"\n\t  }[$__rate_interval:]\n  )\n) by (instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Flow Lookups Processed in Kernel (TOP K)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none", "label": "Packets Hit / sec" }
     ],
     "targets": [
      {
       "expr": "topk($topk, sum(\n    rate(\n      ovs_vswitchd_dp_flows_lookup_hit{\n\t    instance=~\"$instance\"\n\t  }[$__rate_interval:]\n  )\n) by (instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total Offloaded Flows (TOP K)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short", "label": "Packets Hit" }
     ],
     "targets": [
      {
       "expr": "topk($topk, sum(\n    ovs_vswitchd_dp_offloaded_flows_total{\n\t      instance=~\"$instance\"\n\t  }\n) by (instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "PORT ACTION ADD RATE (TOP K)",
     "type": "graph",
     "description": "Rate of number of times a netdev was added as a port from the dpif",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($topk, rate(ovs_vswitchd_dpif_port_add{instance=~\"$instance\"}[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "PORT ACTION DEL RATE (TOP K)",
     "type": "graph",
     "description": "Rate of number of times a netdev was removed as a port from the dpif",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($topk, rate(ovs_vswitchd_dpif_port_del{instance=~\"$instance\"}[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "DP ACTION OVERSIZED RATE ( TOP K )",
     "type": "graph",
     "description": "rate of number of times the translated OpenFlow actions into a datapath actions were too big for a netlink attribute",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($topk, rate(ovs_vswitchd_xlate_actions_oversize{instance=~\"$instance\"}[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "DP OPEN FLOW GET RATE ( TOP K)",
     "type": "graph",
     "description": "Rate of number of times flows were retrieved from the datapath (Linux kernel datapath module)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "topk($topk, rate(ovs_vswitchd_dpif_flow_get{instance=~\"$instance\"}[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "DP OPEN FLOW PUT RATE (TOP K)",
     "type": "graph",
     "description": "Rate of number of times flows were added to the datapath (Linux kernel datapath module)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "topk($topk, rate(ovs_vswitchd_dpif_flow_put{instance=~\"$instance\"}[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "DP OPEN FLOW DEL RATE ( TOP K)",
     "type": "graph",
     "description": "Rate of number of times flows were deleted from the datapath (Linux kernel datapath module)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "topk($topk, rate(ovs_vswitchd_dpif_flow_del{instance=~\"$instance\"}[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "TRANSLATION ACTIONS RATE (TOP K)",
     "type": "graph",
     "description": "Rate of OpenFlow actions were translated into datapath actions",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($topk, rate(ovs_vswitchd_xlate_actions{instance=~\"$instance\"}[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "NETLINK I/O RATE (TOP K AVG)",
     "type": "graph",
     "description": "Rate of netlink messages sent/received by the kernel",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(topk($topk, rate(ovs_vswitchd_netlink_sent{instance=~\"$instance\"}[5m])))",
       "legendFormat": "Sent"
      },
      {
       "expr": "avg(topk($topk, rate(ovs_vswitchd_netlink_received{instance=~\"$instance\"}[5m])))",
       "legendFormat": "Received"
      }
     ]
    },
    {
     "title": "RCONN SENT/QUEUED (TOP K)",
     "type": "graph",
     "description": "Specifies the number of messages that have been sent to the underlying virtual connection (unix, tcp, or ssl) to OpenFlow devices, or queued  because it couldn’t be sent using the underlying virtual connection to OpenFlow devices.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($topk, rate(ovs_vswitchd_rconn_sent{instance=~\"$instance\"}[5m]))",
       "legendFormat": "Sent, {{instance}}"
      },
      {
       "expr": "topk($topk, rate(ovs_vswitchd_rconn_queued{instance=~\"$instance\"}[5m]))",
       "legendFormat": "Queued, {{instance}}"
      }
     ]
    },
    {
     "title": "TXN SUCCESS RATE (TOP K)",
     "type": "graph",
     "description": "\nSpecifies the rate of the OVSDB transaction has successfully completed\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($topk, rate(ovs_vswitchd_txn_success{instance=~\"$instance\"}[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "ABNORMAL TRANSACTIONS",
     "type": "graph",
     "description": "Number of abnormal transactions",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(ovs_vswitchd_txn_error{instance=~\"$instance\"})",
       "legendFormat": "Error"
      },
      {
       "expr": "sum(ovs_vswitchd_txn_aborted{instance=~\"$instance\"})",
       "legendFormat": "Aborted"
      },
      {
       "expr": "sum(ovs_vswitchd_txn_try_again{instance=~\"$instance\"})",
       "legendFormat": "Try Again"
      },
      {
       "expr": "sum(ovs_vswitchd_txn_uncommitted{instance=~\"$instance\"})",
       "legendFormat": "Uncommitted"
      }
     ]
    },
    {
     "title": "VCONN I/O RATE (TOP K)",
     "type": "graph",
     "description": "Specifies the number of messages sent to/received from the OpenFlow Device\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($topk, rate(ovs_vswitchd_vconn_sent{instance=~\"$instance\"}[5m]))",
       "legendFormat": "Sent, {{instance}}"
      },
      {
       "expr": "topk($topk, rate(ovs_vswitchd_vconn_received{instance=~\"$instance\"}[5m]))",
       "legendFormat": "Received, {{instance}}"
      }
     ]
    },
    {
     "title": "ABNORMAL CONNECTIONS",
     "type": "graph",
     "description": "Number of messages that have been dropped causing by flushed queue when reconnecting or queue overflow.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(ovs_vswitchd_rconn_discarded{instance=~\"$instance\"})",
       "legendFormat": "Discarded"
      },
      {
       "expr": "sum(ovs_vswitchd_rconn_overflow{instance=~\"$instance\"})",
       "legendFormat": "Overflow"
      }
     ]
    }
   ]
  },
  {
   "title": "OVS DB (TOP K)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "JSONRPC DETAILS (TOP K)",
     "type": "graph",
     "description": "Shows how many JSON RPC requests actually processed",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($topk, ovs_ovsdb_unixctl_received{instance=~\"$instance\"})",
       "legendFormat": "received, {{instance}}"
      },
      {
       "expr": "topk($topk, ovs_ovsdb_unixctl_replied{instance=~\"$instance\"})",
       "legendFormat": "replied, {{instance}}"
      }
     ]
    },
    {
     "title": "CPU Utilization Rate (TOP K)",
     "type": "graph",
     "description": "TOP K of ovsdb-server process CPU usage",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit", "label": "CPU Util %" }
     ],
     "targets": [
      {
       "expr": "topk($topk, sum(rate(namedprocess_namegroup_cpu_seconds_total{groupname=\"ovsdb-server\",instance=~\"$instance\"}[$__rate_interval])) by (instance) * 100)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory Utilization (TOP K)",
     "type": "timeseries",
     "description": "TOP K of ovsdb-server process RSS memory",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "topk($topk, namedprocess_namegroup_memory_bytes{job=\"process-exporter\",groupname=\"ovsdb-server\",pod=~\"process-exporter-.*\",memtype=\"resident\",instance=~\"$instance\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Datapath (TOP K)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "DP PACKETS RATE (TOP K)",
     "type": "graph",
     "description": "Represents the total number of packets datapath processed which is the sum of “hit” and “missed”",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($topk, rate(ovs_vswitchd_dp_packets_total{instance=~\"$instance\"}[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "PORTS CONNECTED (TOP K)",
     "type": "bargauge",
     "description": "Represents the number of ports connected to the datapath",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk($topk, ovs_vswitchd_dp_if_total{instance=~\"$instance\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "MASKS HIT RATIO (TOP K)",
     "type": "graph",
     "description": "Represents the average number of masks visited per packet",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($topk, ovs_vswitchd_dp_masks_hit_ratio{instance=~\"$instance\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "TOTAL DP FLOWS (TOP K)",
     "type": "graph",
     "description": "Represents the number of flows in datapath.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($topk, ovs_vswitchd_dp_flows_total{instance=~\"$instance\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "MASKS (TOP K)",
     "type": "graph",
     "description": "Represents the number of masks in a datapath",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($topk, ovs_vswitchd_dp_masks_total{instance=~\"$instance\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "upcall_flow_del_rev (TOP K)",
     "type": "graph",
     "description": "Represents the number of times flows were deleted after revalidation determined to delete the flow",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($topk, ovs_vswitchd_upcall_flow_del_rev{instance=~\"$instance\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "upcall_flow_del_no_rev (TOP K)",
     "type": "graph",
     "description": "Represents the number of times flows were deleted because the flow didn't have min-revalidator-pps fulfilled",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($topk, ovs_vswitchd_upcall_flow_del_no_rev{instance=~\"$instance\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "upcall_flow_del_idle_or_limit (TOP K)",
     "type": "graph",
     "description": "Represents the number of times flows were deleted because we reached the limit or flow was idle for more than max-idle time",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($topk, ovs_vswitchd_upcall_flow_del_idle_or_limit{instance=~\"$instance\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "revalidate_missed_dp_flow (TOP K)",
     "type": "graph",
     "description": "Represents the number of times missed datapath flows had to be revalidated",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($topk, ovs_vswitchd_revalidate_missed_dp_flow{instance=~\"$instance\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Bridge (TOP K)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL BRIDGE FLOWS (TOP K)",
     "type": "graph",
     "description": "Total number of OpenFlow flows on the OVS bridge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($topk, ovs_vswitchd_bridge_flows_total{instance=~\"$instance\", bridge=~\"$bridge\"})",
       "legendFormat": "{{instance}},{{bridge}}"
      }
     ]
    },
    {
     "title": "BRIDGE PORTS (TOP K)",
     "type": "bargauge",
     "description": "Number of OVS ports on the bridge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk($topk, ovs_vswitchd_bridge_ports_total{instance=~\"$instance\", bridge=~\"$bridge\"})",
       "legendFormat": "{{instance}},{{bridge}}"
      }
     ]
    },
    {
     "title": "TOTAL BRIDGE FLOWS RATE (TOP K)",
     "type": "graph",
     "description": "Rate of total number of OpenFlow flows on the OVS bridge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "flow/s" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($topk, rate(ovs_vswitchd_bridge_flows_total{instance=~\"$instance\", bridge=~\"$bridge\"}[5m]))",
       "legendFormat": "{{instance}},{{bridge}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Interface (TOP K)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "LINK RESETS RATE (TOP K)",
     "type": "graph",
     "description": "Represents rate of number of times Open vSwitch has observed the link_state of OVS interface change.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "topk($topk, rate(ovs_vswitchd_interface_link_resets{instance=~\"$instance\", bridge=~\"$bridge\", interface=~\"$interface\"}[5m]))",
       "legendFormat": "{{instance}}, {{bridge}}, {{interface}}"
      }
     ]
    },
    {
     "title": "COLLISIONS RATE (TOP K)",
     "type": "graph",
     "description": "Represents rate of number of collisions on interfaces",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "topk($topk, rate(ovs_vswitchd_interface_collisions{instance=~\"$instance\", bridge=~\"$bridge\", interface=~\"$interface\"}[5m]))",
       "legendFormat": "{{instance}}, {{bridge}}, {{interface}}"
      }
     ]
    },
    {
     "title": "OVERRUN ERRORS RATE (TOP K)",
     "type": "graph",
     "description": "Represents rate of RX overrun errors",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "error/s" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "topk($topk, rate(ovs_vswitchd_interface_rx_over_err{instance=~\"$instance\", bridge=~\"$bridge\", interface=~\"$interface\"}[5m]))",
       "legendFormat": "{{instance}}, {{bridge}}, {{interface}}"
      }
     ]
    },
    {
     "title": "FRAME ERRORS RATE (TOP K)",
     "type": "graph",
     "description": "Represents rate of frame errors",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "error/s" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "topk($topk, rate(ovs_vswitchd_interface_rx_frame_err{instance=~\"$instance\", bridge=~\"$bridge\", interface=~\"$interface\"}[5m]))",
       "legendFormat": "{{instance}}, {{bridge}}, {{interface}}"
      }
     ]
    },
    {
     "title": "CRC ERRORS RATE (TOP K)",
     "type": "graph",
     "description": "Represents rate of CRC errors",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "error/s" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "topk($topk, rate(ovs_vswitchd_interface_rx_crc_err{instance=~\"$instance\", bridge=~\"$bridge\", interface=~\"$interface\"}[5m]))",
       "legendFormat": "{{instance}}, {{bridge}}, {{interface}}"
      }
     ]
    },
    {
     "title": "INSTANCE - INTERFACE BANDWIDTH (TOP K)",
     "type": "graph",
     "description": "Represents total received/transmitted bytes by OVS interface.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "topk($topk, rate(ovs_vswitchd_interface_rx_bytes{instance=~\"$instance\", bridge=~\"$bridge\", interface=~\"$interface\"}[5m]))",
       "legendFormat": "{{instance}} - {{interface}} - RX"
      },
      {
       "expr": "topk($topk, rate(ovs_vswitchd_interface_tx_bytes{instance=~\"$instance\", bridge=~\"$bridge\", interface=~\"$interface\"}[5m]))",
       "legendFormat": "{{instance}} - {{interface}} - TX"
      }
     ]
    },
    {
     "title": "NETWORK PACKET RATE (TOP K)",
     "type": "graph",
     "description": "Represents the rate of received/transmitted packets by OVS interface.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "topk($topk, rate(ovs_vswitchd_interface_rx_packets{instance=~\"$instance\", bridge=~\"$bridge\", interface=~\"$interface\"}[5m]))",
       "legendFormat": "{{instance}} - {{interface}} - RX"
      },
      {
       "expr": "topk($topk, rate(ovs_vswitchd_interface_tx_packets{instance=~\"$instance\", bridge=~\"$bridge\", interface=~\"$interface\"}[5m]))",
       "legendFormat": "{{instance}} - {{interface}} - TX"
      }
     ]
    },
    {
     "title": "PACKET I/O ERROR  RATE (TOP 10)",
     "type": "graph",
     "description": "Rate of error received/transmitted packets by OVS interface.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($topk, rate(ovs_vswitchd_interface_rx_errors{instance=~\"$instance\", bridge=~\"$bridge\", interface=~\"$interface\"}[5m]))",
       "legendFormat": "RX, {{instance}}, {{bridge}}, {{interface}}"
      },
      {
       "expr": "topk($topk, rate(ovs_vswitchd_interface_tx_errors{instance=~\"$instance\", bridge=~\"$bridge\", interface=~\"$interface\"}[5m]))",
       "legendFormat": "TX, {{instance}}, {{bridge}}, {{interface}}"
      }
     ]
    },
    {
     "title": "PACKET I/O DROPPED RATE (TOP K)",
     "type": "graph",
     "description": "Rate of dropped received/transmitted packets by OVS interface.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($topk, rate(ovs_vswitchd_interface_rx_dropped{instance=~\"$instance\", bridge=~\"$bridge\", interface=~\"$interface\"}[5m]))",
       "legendFormat": "RX, {{instance}}, {{bridge}}, {{interface}}"
      },
      {
       "expr": "topk($topk, rate(ovs_vswitchd_interface_tx_dropped{instance=~\"$instance\", bridge=~\"$bridge\", interface=~\"$interface\"}[5m]))",
       "legendFormat": "TX, {{instance}}, {{bridge}}, {{interface}}"
      }
     ]
    },
    {
     "title": "VF MISSPKTS DROP RATE (TOP K)",
     "type": "graph",
     "description": "Rate of number of new connection packets dropped on the interface backed by VF",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short", "label": "Packets Dropped / sec" }
     ],
     "targets": [
      {
       "expr": "topk($topk, rate(ovs_vswitchd_interface_tx_misspkts_packets_drops {instance=~\"$instance\", bridge=~\"$bridge\", interface=~\"$interface\"}[5m]))",
       "legendFormat": "{{instance}}, {{bridge}}, {{interface}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Offloads (TOP K)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOP K HW OFFLOAD RATE (BYTES)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "topk($topk, rate(ovs_vswitchd_interface_rx_hw_bytes{instance=~\"$instance\",interface=~\"$interface\"}[$__rate_interval]))",
       "legendFormat": "RX-{{instance}}-{{interface}}"
      },
      {
       "expr": "topk($topk, rate(ovs_vswitchd_interface_tx_hw_bytes{instance=~\"$instance\",interface=~\"$interface\"}[$__rate_interval]))",
       "legendFormat": "TX-{{instance}}-{{interface}}"
      }
     ]
    },
    {
     "title": "TOP K HW OFFLOAD RATE (PACKETS)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "topk($topk, rate(ovs_vswitchd_interface_rx_hw_packets{instance=~\"$instance\",interface=~\"$interface\"}[$__rate_interval]))",
       "legendFormat": "RX-{{instance}}-{{interface}}"
      },
      {
       "expr": "topk($topk, rate(ovs_vswitchd_interface_tx_hw_packets{instance=~\"$instance\",interface=~\"$interface\"}[$__rate_interval]))",
       "legendFormat": "TX-{{instance}}-{{interface}}"
      }
     ]
    },
    {
     "title": "TOP K SW OFFLOAD RATE (BYTES)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "topk($topk, rate(ovs_vswitchd_interface_rx_sw_bytes{instance=~\"$instance\",interface=~\"$interface\"}[$__rate_interval]))",
       "legendFormat": "RX-{{instance}}-{{interface}}"
      },
      {
       "expr": "topk($topk, rate(ovs_vswitchd_interface_tx_sw_bytes{instance=~\"$instance\",interface=~\"$interface\"}[$__rate_interval]))",
       "legendFormat": "TX-{{instance}}-{{interface}}"
      }
     ]
    },
    {
     "title": "TOP K SW OFFLOAD RATE (PACKETS)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "topk($topk, rate(ovs_vswitchd_interface_rx_sw_bytes{instance=~\"$instance\",interface=~\"$interface\"}[$__rate_interval]))",
       "legendFormat": "RX-{{instance}}-{{interface}}"
      },
      {
       "expr": "topk($topk, rate(ovs_vswitchd_interface_tx_sw_bytes{instance=~\"$instance\",interface=~\"$interface\"}[$__rate_interval]))",
       "legendFormat": "TX-{{instance}}-{{interface}}"
      }
     ]
    },
    {
     "title": "TOP K SW BUSY RATE (BYTES)",
     "type": "timeseries",
     "description": "Top K interfaces that sends greater then 100KB of data per second averaging over 15min interval",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "topk($topk, rate(ovs_vswitchd_interface_rx_sw_bytes{instance=~\"$instance\",interface=~\"$interface\"}[5m])>100000)",
       "legendFormat": "RX-{{instance}}-{{interface}}"
      },
      {
       "expr": "topk($topk, rate(ovs_vswitchd_interface_tx_sw_bytes{instance=~\"$instance\",interface=~\"$interface\"}[5m])>100000)",
       "legendFormat": "TX-{{instance}}-{{interface}}"
      }
     ]
    },
    {
     "title": "TOP K SW BUSY RATE (BYTES)",
     "type": "timeseries",
     "description": "Top K interfaces that sends greater then 1000 networking packets of data per second averaging over 15min interval",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "topk($topk, rate(ovs_vswitchd_interface_rx_sw_packets{instance=~\"$instance\",interface=~\"$interface\"}[5m])>1000)",
       "legendFormat": "RX-{{instance}}-{{interface}}"
      },
      {
       "expr": "topk($topk, rate(ovs_vswitchd_interface_tx_sw_packets{instance=~\"$instance\",interface=~\"$interface\"}[5m])>1000)",
       "legendFormat": "TX-{{instance}}-{{interface}}"
      }
     ]
    }
   ]
  }
 ]
}